// Generated by gencpp from file localization/GpsConverterRequest.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_GPSCONVERTERREQUEST_H
#define LOCALIZATION_MESSAGE_GPSCONVERTERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace localization
{
template <class ContainerAllocator>
struct GpsConverterRequest_
{
  typedef GpsConverterRequest_<ContainerAllocator> Type;

  GpsConverterRequest_()
    : gps()  {
    }
  GpsConverterRequest_(const ContainerAllocator& _alloc)
    : gps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _gps_type;
  _gps_type gps;





  typedef boost::shared_ptr< ::localization::GpsConverterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::GpsConverterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GpsConverterRequest_

typedef ::localization::GpsConverterRequest_<std::allocator<void> > GpsConverterRequest;

typedef boost::shared_ptr< ::localization::GpsConverterRequest > GpsConverterRequestPtr;
typedef boost::shared_ptr< ::localization::GpsConverterRequest const> GpsConverterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::GpsConverterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::GpsConverterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localization::GpsConverterRequest_<ContainerAllocator1> & lhs, const ::localization::GpsConverterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gps == rhs.gps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localization::GpsConverterRequest_<ContainerAllocator1> & lhs, const ::localization::GpsConverterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::localization::GpsConverterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::GpsConverterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::GpsConverterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::GpsConverterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::GpsConverterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::GpsConverterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::GpsConverterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6132ea85d83718165933d7eae84ccc5f";
  }

  static const char* value(const ::localization::GpsConverterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6132ea85d8371816ULL;
  static const uint64_t static_value2 = 0x5933d7eae84ccc5fULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::GpsConverterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/GpsConverterRequest";
  }

  static const char* value(const ::localization::GpsConverterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::GpsConverterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point gps\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::localization::GpsConverterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::GpsConverterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsConverterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::GpsConverterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::GpsConverterRequest_<ContainerAllocator>& v)
  {
    s << indent << "gps: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.gps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_GPSCONVERTERREQUEST_H
