// Generated by gencpp from file localization/GpsConverterResponse.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_GPSCONVERTERRESPONSE_H
#define LOCALIZATION_MESSAGE_GPSCONVERTERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace localization
{
template <class ContainerAllocator>
struct GpsConverterResponse_
{
  typedef GpsConverterResponse_<ContainerAllocator> Type;

  GpsConverterResponse_()
    : position()  {
    }
  GpsConverterResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::localization::GpsConverterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization::GpsConverterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GpsConverterResponse_

typedef ::localization::GpsConverterResponse_<std::allocator<void> > GpsConverterResponse;

typedef boost::shared_ptr< ::localization::GpsConverterResponse > GpsConverterResponsePtr;
typedef boost::shared_ptr< ::localization::GpsConverterResponse const> GpsConverterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization::GpsConverterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization::GpsConverterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localization::GpsConverterResponse_<ContainerAllocator1> & lhs, const ::localization::GpsConverterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localization::GpsConverterResponse_<ContainerAllocator1> & lhs, const ::localization::GpsConverterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::localization::GpsConverterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization::GpsConverterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::GpsConverterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization::GpsConverterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::GpsConverterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization::GpsConverterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization::GpsConverterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7bb0ef028c744b081acdc57743b11d8";
  }

  static const char* value(const ::localization::GpsConverterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7bb0ef028c744b0ULL;
  static const uint64_t static_value2 = 0x81acdc57743b11d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::localization::GpsConverterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization/GpsConverterResponse";
  }

  static const char* value(const ::localization::GpsConverterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization::GpsConverterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::localization::GpsConverterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization::GpsConverterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsConverterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization::GpsConverterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization::GpsConverterResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_MESSAGE_GPSCONVERTERRESPONSE_H
