set(_CATKIN_CURRENT_PACKAGE "simulation")
set(simulation_VERSION "0.0.0")
set(simulation_MAINTAINER "tabibwasitrahman <tabibwasitrahman@todo.todo>")
set(simulation_PACKAGE_FORMAT "2")
set(simulation_BUILD_DEPENDS "geometry_msgs" "message_generation" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "visualization_msgs")
set(simulation_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "visualization_msgs")
set(simulation_BUILDTOOL_DEPENDS "catkin")
set(simulation_BUILDTOOL_EXPORT_DEPENDS )
set(simulation_EXEC_DEPENDS "geometry_msgs" "message_runtime" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "visualization_msgs")
set(simulation_RUN_DEPENDS "geometry_msgs" "message_runtime" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "visualization_msgs")
set(simulation_TEST_DEPENDS )
set(simulation_DOC_DEPENDS )
set(simulation_URL_WEBSITE "")
set(simulation_URL_BUGTRACKER "")
set(simulation_URL_REPOSITORY "")
set(simulation_DEPRECATED "")